//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_eveh.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class AERONAVES
    {
        public AERONAVES()
        {
            this.COMPONENTES = new HashSet<COMPONENTES>();
            this.VUELOS = new HashSet<VUELOS>();
        }
    
        public decimal ID { get; set; }
        public string MATRICULA { get; set; }
        public decimal TIPO_AERONAVES_ID { get; set; }
        public string ESTADO { get; set; }
        public System.DateTime FECHA_AERONAVEGABILIDAD { get; set; }
        public System.DateTime FECHA_INSPECCION_ANUAL { get; set; }
        public decimal HORAS_VUELO { get; set; }
        public decimal DIAS_VUELO { get; set; }
    
        public virtual TIPOS_AERONAVES TIPOS_AERONAVES { get; set; }
        public virtual ICollection<COMPONENTES> COMPONENTES { get; set; }
        public virtual ICollection<VUELOS> VUELOS { get; set; }
    }
}
