//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_eveh.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class AERODROMOS
    {
        public AERODROMOS()
        {
            this.VUELOS = new HashSet<VUELOS>();
            this.VUELOS1 = new HashSet<VUELOS>();
        }
    
        public decimal ID { get; set; }
        public string DESCRIPCION { get; set; }
        public string CIUDAD { get; set; }
    
        public virtual ICollection<VUELOS> VUELOS { get; set; }
        public virtual ICollection<VUELOS> VUELOS1 { get; set; }
    }
}
