//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_eveh.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class MANTENIMIENTOS
    {
        public MANTENIMIENTOS()
        {
            this.DETALLES_MANTENIMIENTOS = new HashSet<DETALLES_MANTENIMIENTOS>();
        }
    
        public decimal ID { get; set; }
        public System.DateTime FECHA_INICIO { get; set; }
        public Nullable<System.DateTime> FECHA_TERMINO { get; set; }
    
        public virtual ICollection<DETALLES_MANTENIMIENTOS> DETALLES_MANTENIMIENTOS { get; set; }
    }
}
