//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_eveh.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONAS
    {
        public PERSONAS()
        {
            this.PILOTOS = new HashSet<PILOTOS>();
        }
    
        public decimal ID { get; set; }
        public string RUT { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDOS { get; set; }
        public string SEXO { get; set; }
        public System.DateTime FECHA_NACIMIENTO { get; set; }
        public string TELEFONO { get; set; }
        public string CORREO { get; set; }
        public string NACIONALIDAD { get; set; }
        public decimal USUARIOS_ID { get; set; }
    
        public virtual USUARIOS USUARIOS { get; set; }
        public virtual ICollection<PILOTOS> PILOTOS { get; set; }
    }
}
