//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_eveh.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class PILOTOS
    {
        public PILOTOS()
        {
            this.LICENCIAS = new HashSet<LICENCIAS>();
            this.TRIPULACION = new HashSet<TRIPULACION>();
        }
    
        public decimal ID { get; set; }
        public decimal HORAS_VUELO { get; set; }
        public decimal DIAS_VUELO { get; set; }
        public Nullable<System.DateTime> VENCIMIENTO_MEDICINA { get; set; }
        public Nullable<System.DateTime> ULTIMO_VUELO_REALIZADO { get; set; }
        public decimal PERSONAS_ID { get; set; }
    
        public virtual ICollection<LICENCIAS> LICENCIAS { get; set; }
        public virtual PERSONAS PERSONAS { get; set; }
        public virtual ICollection<TRIPULACION> TRIPULACION { get; set; }
    }
}
