//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_eveh.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRIPULACION
    {
        public decimal VUELOS_ID { get; set; }
        public decimal PILOTOS_ID { get; set; }
        public string TIPO { get; set; }
    
        public virtual PILOTOS PILOTOS { get; set; }
        public virtual VUELOS VUELOS { get; set; }
    }
}
