//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_eveh.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        public USUARIOS()
        {
            this.PERSONAS = new HashSet<PERSONAS>();
        }
    
        public decimal ID { get; set; }
        public string CUENTA { get; set; }
        public string PASS { get; set; }
        public decimal PERFILES_USUARIOS_ID { get; set; }
        public string ESTADO_CUENTA { get; set; }
    
        public virtual PERFILES_USUARIOS PERFILES_USUARIOS { get; set; }
        public virtual ICollection<PERSONAS> PERSONAS { get; set; }
    }
}
